// apps/my-app/src/app/chat/chat-panel.tsx
import React, { useState, useEffect, useRef } from "react";
import { Logger } from "tslog";
import { useChatPanelStore } from "../../features/chat-panel/chat-panel-store";
import { useChatPanelService } from "../../lib/di/di-provider";
import { ChatMessage, ChatMode } from "@repo/events-core/event-types";

const logger = new Logger({ name: "chat-panel" });

// Component for rendering a single chat message
interface ChatMessageItemProps {
  message: ChatMessage;
}

const ChatMessageItem: React.FC<ChatMessageItemProps> = ({ message }) => {
  const isUser = message.role === "USER";
  const isSummarize = message.content.startsWith("[Summarize ✨]");

  // Special handling for system/summary messages
  if (isSummarize) {
    return (
      <div className="my-3 p-3 bg-yellow-50 border-yellow-200 border rounded">
        {message.content}
      </div>
    );
  }

  return (
    <div className={`my-3 ${isUser ? "" : "bg-gray-50 p-3 rounded"}`}>
      <div className="font-medium mb-1">
        {isUser ? "[User]" : "[AI]"}
        {isUser && (
          <button className="ml-2 text-sm text-gray-500 hover:underline">
            [edit]
          </button>
        )}
      </div>
      <div className="whitespace-pre-wrap">{message.content}</div>

      {!isUser && (
        <div className="mt-2 text-sm text-gray-500 flex gap-2">
          <button className="hover:underline">[copy]</button>
          <button className="hover:underline">[retry]</button>
          <button className="hover:underline">[...]</button>
        </div>
      )}
    </div>
  );
};

// Modal component for Next Step functionality
interface NextStepModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (
    prompt: string,
    options: { mode: ChatMode; createNewTask: boolean; model: string }
  ) => void;
}

const NextStepModal: React.FC<NextStepModalProps> = ({
  isOpen,
  onClose,
  onSubmit,
}) => {
  const [prompt, setPrompt] = useState("");
  const [mode, setMode] = useState<ChatMode>("chat");
  const [createNewTask, setCreateNewTask] = useState(true);
  const [model, setModel] = useState("Claude 3.7");

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg p-6 w-full max-w-2xl">
        <h2 className="text-xl font-medium mb-4">Next Step</h2>
        <p className="text-gray-600 mb-4">(AI Suggestions)</p>
        <div className="flex gap-2 mb-4 flex-wrap">
          <button className="px-3 py-1 bg-gray-100 hover:bg-gray-200 rounded">
            [Translate extracted text to Traditional Chinese]
          </button>
          <button className="px-3 py-1 bg-gray-100 hover:bg-gray-200 rounded">
            [Suggestion 2...]
          </button>
          <button className="px-3 py-1 bg-gray-100 hover:bg-gray-200 rounded">
            [Suggestion 3...]
          </button>
        </div>

        <div className="border rounded p-4 mb-4">
          <div className="text-xs font-mono">
            &lt;task_knowledge&gt; #chat_summary.md &lt;/task_knowledge&gt;
            &lt;task_instruction /&gt;
          </div>

          <textarea
            className="w-full border rounded p-2 mt-4"
            rows={5}
            placeholder="Prompt..."
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
          />
        </div>

        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <select
              className="border rounded p-1"
              value={mode}
              onChange={(e) => setMode(e.target.value as ChatMode)}
            >
              <option value="chat">Chat</option>
              <option value="agent">Agent</option>
            </select>

            <label className="flex items-center">
              <input
                type="checkbox"
                checked={createNewTask}
                onChange={(e) => setCreateNewTask(e.target.checked)}
                className="mr-1"
              />
              Create New Task
            </label>

            <select
              className="border rounded p-1"
              value={model}
              onChange={(e) => setModel(e.target.value)}
            >
              <option value="Claude 3.7">Claude 3.7</option>
              <option value="Claude 3.5">Claude 3.5</option>
              <option value="Claude 3">Claude 3</option>
            </select>
          </div>

          <div className="flex gap-2">
            <button
              onClick={onClose}
              className="px-3 py-1 bg-gray-200 hover:bg-gray-300 rounded"
            >
              Cancel
            </button>
            <button
              onClick={() => onSubmit(prompt, { mode, createNewTask, model })}
              className="px-3 py-1 bg-blue-500 text-white hover:bg-blue-600 rounded"
              disabled={!prompt.trim()}
            >
              Submit
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

const ChatPanel: React.FC = () => {
  const {
    currentChat,
    isLoading,
    isResponding,
    messageInput,
    error,
    setMessageInput,
  } = useChatPanelStore();
  const chatPanelService = useChatPanelService();
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const [isNextStepModalOpen, setIsNextStepModalOpen] = useState(false);
  const [chatMode, setChatMode] = useState<ChatMode>("chat");
  const [selectedModel, setSelectedModel] = useState("Claude 3.7");

  // Scroll to bottom of messages when new messages are added
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [currentChat?.messages]);

  // Set initial chat mode from chat metadata
  useEffect(() => {
    if (currentChat?.metadata?.mode) {
      setChatMode(currentChat.metadata.mode);
    }

    if (currentChat?.metadata?.model) {
      setSelectedModel(currentChat.metadata.model);
    }
  }, [currentChat]);

  // Handle send message
  const handleSendMessage = () => {
    if (!messageInput.trim() || !chatPanelService) return;

    chatPanelService.submitUserMessage(messageInput);
  };

  // Handle summarize
  const handleSummarize = () => {
    if (!chatPanelService) return;

    chatPanelService.summarizeChat();
  };

  // Handle attachment button
  const handleAttachment = () => {
    logger.debug("Attachment feature not implemented in MVP");
  };

  // Handle next step modal submit
  const handleNextStepSubmit = (
    prompt: string,
    options: { mode: ChatMode; createNewTask: boolean; model: string }
  ) => {
    if (!chatPanelService) return;

    chatPanelService.createNewChat(prompt, {
      newTask: options.createNewTask,
      mode: options.mode,
      knowledge: ["chat_summary.md"],
      model: options.model,
    });

    setIsNextStepModalOpen(false);
  };

  // Render placeholder when no chat is selected
  if (!currentChat && !isLoading) {
    return (
      <div className="flex items-center justify-center h-full text-gray-400">
        Select a chat or create a new one to start a conversation
      </div>
    );
  }

  // Render loading state
  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-full text-gray-400">
        Loading chat...
      </div>
    );
  }

  // Render error state
  if (error) {
    return (
      <div className="flex items-center justify-center h-full text-red-500">
        Error: {error}
      </div>
    );
  }

  // If for some reason we don't have a chat after all the checks
  if (!currentChat) {
    return null;
  }

  return (
    <div className="h-full flex flex-col">
      {/* Header with path and task info */}
      <div className="p-4 border-b">
        <div className="text-sm text-gray-500">
          🏠 Home &gt; 👥 Workspace
          {currentChat.taskId && <> &gt; 📋 {currentChat.taskId}</>}
          {currentChat.filePath && (
            <> &gt; {currentChat.filePath.split("/").pop()}</>
          )}
        </div>
        <h2 className="text-lg font-medium mt-1">
          {currentChat.metadata?.title ||
            `Chat - ${new Date(currentChat.createdAt).toLocaleString()}`}
        </h2>
      </div>

      {/* Task knowledge section */}
      <div className="px-4 py-2 border-b">
        <details>
          <summary className="font-medium cursor-pointer">
            ▼ Task Knowledge & Instruction
          </summary>
          <div className="border rounded p-2 mt-1">
            <div className="text-xs font-mono">
              <div>
                &lt;task_knowledge&gt;
                {currentChat.metadata?.knowledge?.map((k, i) => (
                  <div key={i}>#{k}</div>
                ))}
                &lt;/task_knowledge&gt;
              </div>
              <div>
                &lt;task_instruction&gt;
                {/* Instruction content would go here */}
                &lt;/task_instruction&gt;
              </div>
            </div>
          </div>
        </details>
      </div>

      {/* Messages area */}
      <div className="flex-grow overflow-y-auto p-4">
        {currentChat.messages.map((message, index) => (
          <ChatMessageItem key={`${message.id || index}`} message={message} />
        ))}

        {isResponding && (
          <div className="p-3 bg-gray-100 rounded mb-3">
            <div className="animate-pulse">AI is responding...</div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Actions and input area */}
      <div className="border-t p-4">
        <div className="flex gap-2 mb-2">
          <button
            onClick={handleSummarize}
            className="px-3 py-1 bg-gray-100 hover:bg-gray-200 rounded text-sm"
          >
            Summarize ✨
          </button>
          <button
            onClick={() => setIsNextStepModalOpen(true)}
            className="px-3 py-1 bg-gray-100 hover:bg-gray-200 rounded text-sm"
          >
            Next Step ▶️✨
          </button>
        </div>

        <div className="flex flex-col">
          <textarea
            className="w-full border rounded p-2 resize-none mb-2"
            placeholder="Write a message..."
            rows={2}
            value={messageInput}
            onChange={(e) => setMessageInput(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                handleSendMessage();
              }
            }}
          />

          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <select
                className="border rounded p-1 text-sm"
                value={chatMode}
                onChange={(e) => setChatMode(e.target.value as ChatMode)}
              >
                <option value="chat">Chat</option>
                <option value="agent">Agent</option>
              </select>

              <select
                className="border rounded p-1 text-sm"
                value={selectedModel}
                onChange={(e) => setSelectedModel(e.target.value)}
              >
                <option value="Claude 3.7">Claude 3.7</option>
                <option value="Claude 3.5">Claude 3.5</option>
                <option value="Claude 3">Claude 3</option>
              </select>
            </div>

            <div className="flex gap-2">
              <button
                onClick={handleAttachment}
                className="px-2 py-1 bg-gray-100 hover:bg-gray-200 rounded text-sm"
              >
                📎 Attach
              </button>

              <button
                onClick={handleSendMessage}
                disabled={!messageInput.trim() || isResponding}
                className={`px-3 py-1 rounded text-sm ${
                  !messageInput.trim() || isResponding
                    ? "bg-blue-300 text-white cursor-not-allowed"
                    : "bg-blue-500 text-white hover:bg-blue-600"
                }`}
              >
                Send ➤
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Next Step Modal */}
      <NextStepModal
        isOpen={isNextStepModalOpen}
        onClose={() => setIsNextStepModalOpen(false)}
        onSubmit={handleNextStepSubmit}
      />
    </div>
  );
};

export default ChatPanel;

// apps/my-app-svelte/src/components/ChatPanel.svelte
<!-- apps/my-app-svelte/src/components/ChatPanel.svelte -->
<script lang="ts">
  import { tick } from "svelte";
  import {
    hasCurrentChat,
    currentChat,
    currentChatMessages,
    currentChatBreadcrumb,
    messageInput,
    updateMessageInput,
    chatMode,
    selectedModel,
    extractFileReferences,
  } from "../stores/chat-store";
  import { connectionStates, isLoading, showToast } from "../stores/ui-store";
  import { chatService } from "../services/chat-service";
  import {
    Send,
    Paperclip,
    ChevronDown,
    ChatDots,
    Pencil,
    Copy,
    ThreeDots,
    HouseDoor,
    ChevronRight,
    Download,
    Lightbulb,
    FileEarmark,
    ArrowClockwise,
  } from "svelte-bootstrap-icons";
  import { Logger } from "tslog";

  const logger = new Logger({ name: "ChatPanel" });

  let messageInputElement = $state<HTMLTextAreaElement>();
  let messagesContainer = $state<HTMLDivElement>();
  let draftTimeout: NodeJS.Timeout;

  // Auto-scroll to bottom when new messages arrive using $effect
  $effect(() => {
    if ($currentChatMessages && messagesContainer) {
      tick().then(() => {
        messagesContainer.scrollTop = messagesContainer.scrollHeight;
      });
    }
  });

  // Auto-save draft when input changes using $effect
  $effect(() => {
    if ($currentChat && $messageInput.trim()) {
      clearTimeout(draftTimeout);
      draftTimeout = setTimeout(() => {
        chatService.savePromptDraft($currentChat!.id, $messageInput);
      }, 1500);
    }
  });

  async function handleSendMessage() {
    if (!$messageInput.trim() || !$currentChat) return;

    const message = $messageInput.trim();
    const chatId = $currentChat.id;

    try {
      await chatService.submitMessage(chatId, message);
    } catch (error) {
      // Error handling done in service
    }
  }

  function handleKeyPress(event: KeyboardEvent) {
    if (event.key === "Enter" && !event.shiftKey) {
      event.preventDefault();
      handleSendMessage();
    }
  }

  function handleRefreshChat() {
    if (!$currentChat) return;

    chatService.openChatFile($currentChat.absoluteFilePath);
  }

  function formatTimestamp(timestamp: Date): string {
    return new Date(timestamp).toLocaleTimeString([], {
      hour: "2-digit",
      minute: "2-digit",
    });
  }

  function handleCopyMessage(content: string) {
    navigator.clipboard.writeText(content);
    showToast("Message copied to clipboard", "success");
  }

  function handleEditMessage() {
    showToast("Edit functionality not implemented yet", "info");
  }

  function handleMoreAction(action: string) {
    showToast(`${action} functionality coming soon`, "info");
  }

  function handleFileReference(filePath: string) {
    // TODO: Open file in preview or explorer
    showToast(`Open ${filePath} functionality coming soon`, "info");
  }

  function handleWhatsNext() {
    showToast(
      "What's Next: Analyze your recent code changes for patterns.",
      "info",
    );
  }

  function handleSummarize() {
    showToast("Chat summary functionality coming soon", "info");
  }

  // Chat mode and model options
  const chatModeOptions = [
    { value: "chat", label: "Chat" },
    { value: "agent", label: "Agent" },
  ];

  const modelOptions = [
    { value: "claude", label: "Claude 3.7" },
    { value: "gemini", label: "Gemini 2.5 Pro" },
  ];

  // Cleanup timeout on component destroy using $effect
  $effect(() => {
    return () => {
      clearTimeout(draftTimeout);
    };
  });
</script>

<div class="bg-background flex min-w-0 flex-1 flex-col">
  {#if $hasCurrentChat}
    <!-- Breadcrumb Header -->
    <header
      class="bg-surface border-border flex h-12 items-center gap-2 border-b px-4"
    >
      <HouseDoor class="text-muted text-sm" />
      {#if $currentChatBreadcrumb}
        <span class="text-muted text-xs"
          >{$currentChatBreadcrumb.parentDir}</span
        >
        <ChevronRight class="text-muted text-xs" />
        <span class="text-muted text-xs">{$currentChatBreadcrumb.fileName}</span
        >
      {/if}
      <div class="ml-auto flex items-center space-x-2">
        <button
          onclick={handleRefreshChat}
          disabled={$isLoading("openChat")}
          class="bg-panel hover:bg-hover text-muted rounded px-2 py-1 text-xs disabled:opacity-50"
        >
          <ArrowClockwise class="text-xs" />
          {$isLoading("openChat") ? "Refreshing..." : "Refresh"}
        </button>
        <div class="text-muted text-xs">
          {#if $connectionStates.chatEvents === "connected"}
            <span class="text-green-400">🟢 Live</span>
          {:else if $connectionStates.chatEvents === "connecting"}
            <span class="text-yellow-400">🟡 Connecting</span>
          {:else if $connectionStates.chatEvents === "error"}
            <span class="text-red-400">🔴 Disconnected</span>
          {:else}
            <span class="text-muted">⚪ Idle</span>
          {/if}
        </div>
      </div>
    </header>

    <!-- Messages Area -->
    <div
      bind:this={messagesContainer}
      class="bg-background flex-1 space-y-5 overflow-y-auto px-8 py-6"
    >
      {#each $currentChatMessages as message (message.id)}
        {#if message.role === "USER"}
          <!-- User Message -->
          <div class="group flex flex-col items-end">
            <div
              class="bg-accent/20 border-accent/30 text-foreground ml-auto max-w-xl rounded-lg border px-4 py-2"
            >
              <!-- File References -->
              {@const fileReferences = extractFileReferences(message.content)}
              {#if fileReferences.length > 0}
                <div class="mb-2 flex flex-wrap gap-1">
                  {#each fileReferences as ref}
                    <button
                      onclick={() => handleFileReference(ref.path)}
                      class="text-accent hover:text-accent/80 text-sm underline"
                    >
                      #{ref.path}
                    </button>
                  {/each}
                </div>
              {/if}

              <!-- Message Content -->
              <div class="leading-normal whitespace-pre-wrap">
                {message.content}
              </div>

              <!-- Timestamp -->
              <div class="text-accent/60 mt-2 text-xs">
                {formatTimestamp(message.timestamp)}
              </div>
            </div>

            <!-- Message Actions -->
            <div
              class="mt-1 flex items-center gap-3 opacity-0 transition-opacity group-hover:opacity-100 mr-2"
            >
              <button
                onclick={() => handleEditMessage()}
                class="text-muted hover:text-accent"
                title="Edit"
              >
                <Pencil class="text-sm" />
              </button>
              <button
                onclick={() => handleCopyMessage(message.content)}
                class="text-muted hover:text-accent"
                title="Copy"
              >
                <Copy class="text-sm" />
              </button>
              <button
                onclick={() => handleMoreAction("More options")}
                class="text-muted hover:text-accent"
                title="More"
              >
                <ThreeDots class="text-sm" />
              </button>
            </div>
          </div>
        {:else}
          <!-- Assistant Message -->
          <div class="group flex flex-col items-start">
            <div class="mb-0.5 flex items-center gap-2">
              <span
                class="bg-accent flex h-5 w-5 items-center justify-center rounded-full text-xs font-bold text-white"
              >
                C
              </span>
              <span class="text-muted text-xs font-medium">Claude Sonnet 4</span
              >
              <span class="text-muted text-xs"
                >{formatTimestamp(message.timestamp)}</span
              >
            </div>

            <div class="text-foreground pl-7 leading-normal">
              <!-- Message Content -->
              <div class="whitespace-pre-wrap">{message.content}</div>

              <!-- Artifacts (placeholder) -->
              {#if message.content.includes("artifact") || message.content.includes("wireframe")}
                <div class="mt-2">
                  <button
                    onclick={() => handleMoreAction("Preview artifact")}
                    class="border-border bg-panel hover:bg-hover text-foreground flex items-center gap-2 rounded border px-3 py-1 text-sm font-medium"
                  >
                    <FileEarmark class="text-sm" />
                    wireframe.html
                    <span class="text-muted ml-1 text-xs">v3</span>
                    <button
                      onclick={(e) => {
                        e.stopPropagation();
                        handleMoreAction("Download artifact");
                      }}
                      class="text-muted hover:text-accent ml-2"
                      title="Download"
                    >
                      <Download class="text-sm" />
                    </button>
                  </button>
                </div>
              {/if}
            </div>

            <!-- Message Actions -->
            <div
              class="mt-1 flex items-center gap-3 opacity-0 transition-opacity group-hover:opacity-100 ml-7"
            >
              <button
                onclick={() => handleEditMessage()}
                class="text-muted hover:text-accent"
                title="Edit"
              >
                <Pencil class="text-sm" />
              </button>
              <button
                onclick={() => handleCopyMessage(message.content)}
                class="text-muted hover:text-accent"
                title="Copy"
              >
                <Copy class="text-sm" />
              </button>
              <button
                onclick={() => handleMoreAction("More options")}
                class="text-muted hover:text-accent"
                title="More"
              >
                <ThreeDots class="text-sm" />
              </button>
            </div>
          </div>
        {/if}
      {/each}

      <!-- Loading indicator for AI response -->
      {#if $isLoading("submitMessage")}
        <div class="flex items-start">
          <span
            class="bg-accent flex h-5 w-5 items-center justify-center rounded-full text-xs font-bold text-white"
          >
            C
          </span>
          <div class="text-muted ml-3 text-sm">
            <div class="flex items-center gap-2">
              <div class="animate-pulse">Thinking...</div>
              <div class="flex space-x-1">
                <div class="h-1 w-1 bg-muted rounded-full animate-pulse"></div>
                <div
                  class="h-1 w-1 bg-muted rounded-full animate-pulse delay-75"
                ></div>
                <div
                  class="h-1 w-1 bg-muted rounded-full animate-pulse delay-150"
                ></div>
              </div>
            </div>
          </div>
        </div>
      {/if}
    </div>

    <!-- Input Area -->
    <footer class="border-border bg-panel border-t px-6 py-4">
      <div class="relative">
        <textarea
          bind:this={messageInputElement}
          bind:value={$messageInput}
          oninput={(e) => updateMessageInput(e.currentTarget.value)}
          onkeypress={handleKeyPress}
          placeholder="Type your message..."
          class="bg-input-background border-input-border focus:border-accent placeholder-muted text-foreground w-full resize-none rounded-md border px-3 py-3 text-[15px] focus:outline-none"
          rows="3"
          disabled={$isLoading("submitMessage")}
        ></textarea>
      </div>

      <!-- Controls below input -->
      <div class="mt-2 flex flex-wrap items-center gap-3">
        <button
          onclick={() => showToast("Attach functionality coming soon", "info")}
          class="text-muted hover:text-accent"
          title="Attach"
        >
          <Paperclip class="text-base" />
        </button>

        <!-- Chat Mode Select -->
        <select
          bind:value={$chatMode}
          class="bg-panel border-border hover:bg-hover focus:border-accent text-muted rounded border px-3 py-1 text-xs focus:outline-none"
        >
          {#each chatModeOptions as option}
            <option value={option.value}>{option.label}</option>
          {/each}
        </select>

        <!-- Model Select -->
        <select
          bind:value={$selectedModel}
          class="bg-panel border-border hover:bg-hover focus:border-accent text-muted rounded border px-3 py-1 text-xs focus:outline-none"
        >
          {#each modelOptions as option}
            <option value={option.value}>{option.label}</option>
          {/each}
        </select>

        <button
          onclick={handleWhatsNext}
          class="text-muted hover:text-accent flex items-center text-xs"
        >
          <Lightbulb class="mr-1 text-sm" />
          What's next
        </button>

        <button
          onclick={handleSummarize}
          class="text-muted hover:text-accent flex items-center text-xs"
        >
          <FileEarmark class="mr-1 text-sm" />
          Summarize
        </button>

        <!-- Send button -->
        <button
          onclick={handleSendMessage}
          disabled={!$messageInput.trim() || $isLoading("submitMessage")}
          class="hover:bg-accent/80 bg-accent text-white ml-auto rounded px-3 py-1.5 disabled:cursor-not-allowed disabled:opacity-50"
          title="Send"
        >
          <Send class="text-base" />
        </button>
      </div>
    </footer>
  {:else}
    <!-- No Chat Selected -->
    <div class="bg-background flex flex-1 items-center justify-center">
      <div class="text-muted text-center">
        <ChatDots class="mx-auto mb-4 text-5xl" />
        <p class="mb-2">Select a chat file to start</p>
        <p class="text-xs opacity-75">
          Create a new chat from the file explorer
        </p>
      </div>
    </div>
  {/if}
</div>
